"""empty message

Revision ID: 273b5fa5c447
Revises: 4ca5f247d924
Create Date: 2018-08-24 01:58:19.816741

"""

# revision identifiers, used by Alembic.
revision = '273b5fa5c447'
down_revision = '4ca5f247d924'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
